language: java
script: mvn -s .settings.xml clean javadoc:jar source:jar package install deploy
jdk:
- oraclejdk8
env:
  global:
    secure: uVagnPZXLO6biv4qOf2HSUPHV5C/tPnJoHTlGYUY6x7USccRPMBiOF0OYv8Pgh3CRL4Q9jojpvCwFN/yM6Xz7bw76x3/ckAU0/q46ZY57I2xCF1dv+uiRF9qwdLuKbH5eSfaqFcmSq+yOvLWhisDqZCLIYI0FItzPOZzsVzULq2GxzhWQxxsAjijIiB3qzPgRwVI+53SfsbmUGfQcffsTgN7ArKhSDYkvJX0kSkQSAer9ipKPRyAlxMt7aMOossEOUUdlzymLuaU46FFQZ6HxBuTkNFPNb+m0Wljs+9vXvKhIQLahzf/G8/B+IXO/Ee2agjtoTTusYXHG28lRfuFoSbq7wH2Nq47NEuul+3vDTvxpMO0GwulrRpSsf8S6g4P31vYqq86+dSZfb/mUYf6BvsAmavSR5DwglSeyVqtHszwk7XB3SA0BFzF8g/Ps3FHOXV2EcMx9z2bKBNiUx7dE8bikeTJc1NbkQLckw9150ZmC9oh6ZsmOjmGy5pJ5AHQvy9M1A4rMn9ZoW/5rJcJraQU3uV6WMXByyFPHcTyN6jVqA4iAijZUv4MDY9sgSUnjqvRzHR+sRAORag+8+HVuZVvLItZSqgnGVXlc02xVZ7uKOngFNArBXsRS/i5IcYC54EZ6UjXOn3ZIFU6RKFg81AuBRUicDOiuE77ZzPQq6M=
